# Changes here will be overwritten by Copier
_commit: 1.0.1
_src_path: .
copyright_date: '2023'
copyright_holder: Apexive.com
copyright_holder_email: support@apexive.com
enable_asgi: true
google_project: django-df-chat
media_storage_cache_urls: false
media_storage_public: false
organisation: djangoflow
project_description: djangoflow-df-chat
project_name: df-chat
repository_name: django-df-chat
