# Generated by Django 5.0.3 on 2024-03-05 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("df_chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="message_type",
            field=models.IntegerField(
                choices=[
                    (0, "Regular message"),
                    (1, "Message response"),
                    (2, "Reaction"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="df_chat.chatmessage",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["parent"], name="df_chat_cha_related_9cf836_idx"
            ),
        ),
    ]
