# Generated by Django 4.2.3 on 2023-07-11 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("df_chat", "0002_remove_roomuser_is_online_userchat"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate, new table
                # name from AuthorBook._meta.db_table.
                migrations.RunSQL(sql="ALTER TABLE df_chat_room_users RENAME TO df_chat_removable_room_users",
                                  reverse_sql="ALTER TABLE df_chat_removable_room_users RENAME TO df_chat_room_users"
                                  )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="room",
                    name="users",
                    field=models.ManyToManyField(
                        blank=True, through="df_chat.RoomUser", to=settings.AUTH_USER_MODEL
                    ),
                )
        ])

    ]
