# Generated by Django 4.2.1 on 2023-05-26 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('df_chat', '0002_remove_roomuser_is_online_userchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, through='df_chat.RoomUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
