name: code_checks
on: [pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: python -m venv venv
      - run: pip install -r requirements-dev.txt
      - run: pre-commit install
      - run: source venv/bin/activate && pre-commit run --all-files --show-diff-on-failure

  unit_tests:
    needs: [pre-commit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: python -m venv venv
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: source venv/bin/activate
      - run: python manage.py migrate
      - run: python manage.py test
